### PR TITLE
PRESS4-401 Add to cart event

### PR DESCRIPTION
**Pull request by mamatharao05**
Ticket: [PRESS4-401](https://jira.newfold.com/browse/PRESS4-401)

Updated hook to trigger only when the cart is updated.

### CODE REVIEW

**Comment by earnjam** [comment]
This is the same hook [I just removed](https://github.com/newfold-labs/wp-module-data/commit/668edee6dd6e901e1fc4c6ddf43f221b5f8e04f3) for firing way too frequently. If it's supposed to be a cart added event, as the naming implies, then it should probably use `woocommerce_add_cart_item`. 

But regardless of the specific hook to use here, I think before we add any cart-driven events we need to have a broader discussion about the pros/cons of using front-end hooks for events.

**Comment by mamatharao05** [comment]
I have noticed the hooks '**woocommerce_add_cart_item**' and '**woocommerce_add_to_cart**' don't seem to be triggered when the same item is added again, they appear to fire only when a new item is added to the cart. As a workaround, I started using the 'cart updated' event. I will continue exploring other hooks to find a more suitable solution.

**Comment by wpscholar** [comment]
@mamatharao05 The stance on this at the moment is to hold for now.

**Comment by circlecube** [comment]
Closing this as it is outdated. We'll open a new PR if this issue comes up again.

**Pull request closed without merging**
