### PR TITLE
Add Hiive Token to Wonder Blocks Platform API requests

### PR DESCRIPTION
**Pull request by arunshenoy99**
## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

This update adds an `X-Hiive-Token` to all outgoing Wonder Blocks Platform API requests. This goes with https://github.com/newfold-labs/wp-module-patterns/pull/73 which updates the patterns module to utilize the common helpers. The helpers in this folder will become the standard interface for interacting with the Wonder Blocks API platform.

### CODE REVIEW

**Comment by BrianHenryIE** [comment]
Hey @arunshenoy99 just a few notes, not all directly to the changes today but things I changed as I saw them:

```
/**
 * The primary type query parameter. See SiteClassification/PrimaryType for information on primary types.
 */
```

```
/**
 * The primary type query parameter. {@see \NewfoldLabs\WP\Module\Data\SiteClassification\PrimaryType} for information on primary types.
 */
```

This `{@see Classname}` inside a docblock (doesn't work in just a `//` comment) turns the classname into a link in your IDE.

`boolean` and `integer` type hints are more correctly `bool` and `int`

I added what I think is the correct `$args` constructor parameter shape. See [PHPStan PHPDoc array shapes](https://phpstan.org/writing-php-code/phpdoc-types#array-shapes).

I changed the static function to a instance method. They're easier to work with when testing.

We increased the minimum PHP version to 7.3 recently so I was able to add return types to the methods (but not yet to the properties, that requires 7.4).

I wrapped the use of constants, e.g. `NFD_DATA_WB_DEV_MODE`, with the `constant()` function, e.g. `constant( 'NFD_DATA_WB_DEV_MODE' )`, which makes it possible to mock the return value in tests to better control the test and cover all possible paths.

I extracted the `if ( ! ( defined( 'NFD_DATA_WB_DEV_MODE' ) && NFD_DATA_WB_DEV_MODE ) ) {` to its own method for clarity, and commented.

And besides that just wrote tests covering the new functionality.

One thing I didn't like is that `Fetch::get_url()` can return an empty string if the `endpoint` key isn't present in the constructor argument array. I'd avoid using arrays in constructors like this for clarity and safety. I'm not familiar enough with this to suggest changing it, and it works, so that's good enough!

**Comment by arunshenoy99** [comment]
> Hey @arunshenoy99 just a few notes, not all directly to the changes today but things I changed as I saw them:
> 
> ```
> /**
>  * The primary type query parameter. See SiteClassification/PrimaryType for information on primary types.
>  */
> ```
> 
> ```
> /**
>  * The primary type query parameter. {@see \NewfoldLabs\WP\Module\Data\SiteClassification\PrimaryType} for information on primary types.
>  */
> ```
> 
> This `{@see Classname}` inside a docblock (doesn't work in just a `//` comment) turns the classname into a link in your IDE.
> 
> `boolean` and `integer` type hints are more correctly `bool` and `int`
> 
> I added what I think is the correct `$args` `Fetch` constructor parameter shape. See [PHPStan PHPDoc array shapes](https://phpstan.org/writing-php-code/phpdoc-types#array-shapes).
> 
> I changed the static `Request::get_base_url()` function to a instance method. They're easier to work with when testing.
> 
> We increased the minimum PHP version to 7.3 recently so I was able to add return types to the methods (but not yet to the properties, that requires 7.4).
> 
> I wrapped the use of constants, e.g. `NFD_DATA_WB_DEV_MODE`, with the `constant()` function, e.g. `constant( 'NFD_DATA_WB_DEV_MODE' )`, which makes it possible to mock the return value in tests to better control the test and cover all possible paths.
> 
> I extracted the `if ( ! ( defined( 'NFD_DATA_WB_DEV_MODE' ) && NFD_DATA_WB_DEV_MODE ) ) {` to its own method for clarity, and commented.
> 
> And besides that just wrote tests covering the new functionality. In particular this test to assert the token is in the request:
> 
> https://github.com/newfold-labs/wp-module-data/blob/814f6e4fa37664df2fe864fe32a3c2bb810f221c/tests/phpunit/includes/WonderBlocks/WonderBlocksTest.php#L43-L54
> 
> One thing I didn't like is that `Fetch::get_url()` can return an empty string if the `endpoint` key isn't present in the constructor argument array. I'd avoid using arrays in constructors like this for clarity and safety. I'm not familiar enough with this to suggest changing it, and it works, so that's good enough!

Thanks! @BrianHenryIE I will keep these in mind for next time. I believe we don't yet have a working unit test runner on GitHub, so I was able to verify the changes locally. If there are no more changes needed, could you please approve the PR? Then, I can move it forward for a round of QA testing.

**Review by BrianHenryIE — APPROVED** [review]

**Comment by BrianHenryIE** [comment]
@arunshenoy99 Good catch! I updated the tests to work with your change. I saw a bug in my work too so added more tests. I'll take a look at adding them to the GitHub Actions workflows soon, as well as documenting how to run them locally too.

**Review by arunshenoy99 — COMMENTED** [review]
QA confirmed that these changes work well. @BrianHenryIE, can you please merge the PR and tag a release so the patterns team can update the version in their repository as well? Thanks!

**Pull request merged**
